import { Field } from '../app/create/field.model';

export const APP_CONSTANTS = {
  HEADER: {
    APP_TITLE: 'AI Digital Assistant (ADA)',
    NOTIFICATION_TOOLTIP: 'Notification',
    MY_ACCOUNT_TOOLTIP: 'My Account',
    USER_INITIALS: 'JD',
  },
  LEFT_NAV: {
    LOGO_TEXT: 'Avolta',
    CREATE: 'Create',
    CREATE_TOOLTIP: 'Create new BIC',
    HOME: 'Home',
    HOME_TOOLTIP: 'Home',
    REQUEST: 'Request',
    REQUEST_TOOLTIP: 'My Request',
    DRAFTS: 'Drafts',
    NO_DRAFTS: 'No drafts',
    DELETE_CONFIRM_TITLE: 'Are you sure you want to delete',
    DELETE_CONFIRM_SUFFIX: 'draft ?',
    DELETE_CONFIRM_BODY_1:
      'All data related to this idea will be permanently removed.',
    DELETE_CONFIRM_BODY_2:
      'You will lose any progress and will not be able to recover it.',
    DELETE_CONFIRM_FOOTER: 'Please confirm your decision before proceeding.',
    CANCEL: 'Cancel',
    LET_ME_EDIT: 'Let me edit',
    DELETE: 'Delete',
    OPEN_TOOLTIP: 'Open',
    SUCCESS: 'Success',
    DELETE_SUCCESS: 'Successfully delete the bic',
    YOUR_IDEA_TITLE: 'Your Idea Title',
    ADA_STATIC_TEXT:
      "ADA couldn't fill this field, please continue the conversation to fill it",
  },
  CAROUSEL: {
    FIRST_TITLE: 'Let’s create something amazing together🌟',
    LIST_ITEMS: [
      `You will be asked about your project idea, and our 
       <strong>Artificial Intelligence Digital Assistant</strong> (ADA) 
       will generate a project overview for you.`,

      'The form on the right will be automatically populated as you chat with ADA',

      'You can review and edit your response at any time',
    ],
    FIRST_TITLE_NO: '1',
    FIRST_GUIDE_TITLE: 'How it works?',
    SECOND_TITLE_NO: '2',
    SECOND_GUIDE_TITLE:
      'ADA will pre-fill all the key fields required for your idea.',
    SECOND_GUIDE_DESCRIPTION:
      'You’ll need to review and confirm the ADA generated data. Make any necessary edits before proceeding.',
    SECOND_LIST_ITEMS: [
      'Title',
      'Problem statement',
      'Objective',
      'Key Result',
      'Key Feature',
      'Urgency',
      'Area involved',
      'Destination 2027 alignment',
      'Risks',
    ],
    THIRD_TITLE_NO: '3',
    THIRD_GUIDE_TITLE: 'Additional fields to enhance your idea',
    THIRD_GUIDE_DESCRIPTION:
      'Adding additional details can help make your submission more compelling and comprehensive.',
    THIRD_PART_ONE: 'Part 1',
    THIRD_PART_ONE_LIST: [
      'KPIs',
      'Data needed',
      'Impact',
      'Implementation considerations',
    ],
    THIRD_PART_TWO: 'Part 2',
    THIRD_PART_TWO_LIST: [
      'Dependencies',
      'Key dates',
      'Estimated timeline',
      'Business sponsor',
    ],
    THIRD_PART_THREE: 'Part 3',
    THIRD_PART_THREE_LIST: [
      'Budget details',
      'Stakeholders',
      'Out of scope',
      'Business case impacts',
    ],
    THIRD_PART_FOUR: 'Part 4',
    THIRD_PART_FOUR_LIST: [
      'Portfolio alignment',
      'IT sponsor',
      'Additional documentations',
      'Additional comments',
    ],

    FOURTH_TITLE_NO: '4',
    FOURTH_GUIDE_TITLE: 'Tips for a strong submission',
    FOURTH_LIST_ONE: [
      'Be clear and specific about the problem your idea solves.',
      'Define measurable objectives and key results.',
      'Include stakeholders and consider their roles in implementation.',
      'Think ahead by identifying risks, dependencies, and timelines.',
      'Ensure alignment with strategic goals, such as Destination 2027.',
      'Provide all available information to ensure you cover all the necessary details',
    ],
    FOURTH_DONT_WORRY: 'ADA’s got you! Don’t worry',
    FOURTH_LIST_TWO: [
      ' Our system will guide you through every step of the process,providing prompts and support as you go. You can always come back and edit your responses later if needed.',
      `When you're ready, click <b>Get started</b> to begin crafting your idea. Let’s make it amazing!'`,
    ],
    PREVIOUS: 'Previous',
    LET_ME_SKIP: 'Let me skip',
    NEXT: 'Next',
    GET_STARTED: 'Get started',
  },
  CREATE: {
    bot_default_message:
      'Let’s start by understanding your idea. Give me a brief overview, covering the key challenge and what you want to achieve',
    bot_default_guideText: [
      'What’s the problem? (What needs fixing or improving?)',
      'What’s your goal? (What do you want to achieve?)',
      'How will success be measured? (Think metrics or key results.)',
      'Is there urgency? (Any deadlines, priorities, or risks?)',
    ],
    bot_default_following: [
      'Text input (Type your response)',
      'Attachment (Upload a PDF, Word, PPT or Excel file)',
      'Voice input (Record your response)',
    ],
    guideQuestionTitle:
      'Let’s start with the basics! Share a brief description of your idea, covering',
    followingQuestionTitle:
      'You can provide your response in one of the following ways',
    draftSaved: 'Your draft has been saved.',
    additionalText: 'Additional comments',
    generatedText: 'Generated text will appear here',
    statusPending: 'Pending-review',
    char: 'abcdefghijklmnopqrstuvwxyz0123456789',
    enter: 'Enter',
    true: 'True',
    false: 'False',
    senderUser: 'user',
    senderBot: 'bot',
    question: 'Question',
    guidelines: 'Guidelines',
    goodToMe: 'All looks good to me',
    ADAtext:
      'This field was pre-filled by ADA based on your conversation. Please review and edit as needed.',
    portfolioText: 'Portfolio alignment',
    itSponsorText: 'IT sponsor',
    timelinesText: 'Timelines',
    areaInvolvedText: 'Areas involved',
    destinationText: 'Destination 2027 alignment',
    businessSponsorText: 'Business sponsor',
    bussinessImpactText: 'Business case impacts',
    kpisText: 'KPIs',
    dataNeededText: 'Data needed',
    additionalAttachmentsText: 'Additional attachments',
    successADAContent: 'Successfully accepted the ADA-generated content',
    successContent: 'Your idea has been successfully created!',
    deleteFile: 'Successfully delete the file',
    yesEverything: 'Yes, everything looks good',
    attachFile: 'Successfully attached the file',
    noInformation: 'NO INFORMATION PROVIDED',
    largerThan: 'You may not upload files larger than 20mb',
    nextSteps: 'Next steps',
    errorDiv: 'There is some error while uploading the file, please try again',
    ADA_STATIC_TEXT:
      "ADA couldn't fill this field, please continue the conversation to fill it",
    covertional: 'Conversational assistant',
    guidanceText: 'Guidance text',
    confirmText: 'Confirm',
    yourIdeaTitle: 'Your business idea overview',
    Progress: 'Progress',
    complete: 'Completed',
    required: 'Required key fields',
    AllGoodButton: 'All details look good',
    notFilled: 'Not filled yet',
    drag: 'Drag and drop or ',
    choose: 'choose files',
    download: 'Download',
    delete: 'Delete',
    add: 'Add',
    finalContent:
      'This is not the final content until you confirm it. Generated by AI.',
    additional: 'Additional fields',
    submit: 'Submit',
    review: 'Please review your idea',
    reviewDetail:
      'Before submitting, please review the details you’ve provided and the fields we’ve auto-filled. Make sure everything looks correct and complete.',
    CANCEL: 'Cancel',
    edit: 'Let me edit',
    langForChat: 'en_US',
    sorryNetworkText:
      'Sorry for trouble,there is some network issues please try again',
    notSupportedText: 'Files of following format is not supported',
    fileSizeExceededText: 'You may not upload files larger than 20mb',
    noCheck: "No, I'd like to review and make edits",
  },
  FIELDS: <Field[]>[
    {
      label: 'Your idea title',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/title.svg',
      completed: false,
      tooltip: 'Add static text here',
    },
    {
      label: 'Problem statement',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/problem-statement.svg',
      completed: false,
    },
    {
      label: 'Objective',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/objective.svg',
      completed: false,
    },
    {
      label: 'Key results',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/key-result.svg',
      completed: false,
    },
    {
      label: 'Key features',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/key-feature.svg',
      completed: false,
    },
    {
      label: 'Urgency',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/urgency.svg',
      completed: false,
    },
    {
      label: 'Areas involved',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/area-involved.svg',
      completed: false,
    },
    {
      label: 'Destination 2027 alignment',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/destination.svg',
      completed: false,
    },
    {
      label: 'Risks',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/risk.svg',
      completed: false,
    },
    {
      label: 'KPIs',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/key-result.svg',
      completed: false,
    },
    {
      label: 'Data needed',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/data-needed.svg',
      completed: false,
    },
    {
      label: 'Impact',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/impact.svg',
      completed: false,
    },
    {
      label: 'Implementation considerations',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/implementation.svg',
      completed: false,
    },
    {
      label: 'Dependencies',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/dependencies.svg',
      completed: false,
    },
    {
      label: 'Key dates',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/key-dates.svg',
      completed: false,
    },
    {
      label: 'Timelines',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/timeline.svg',
      completed: false,
    },
    {
      label: 'Business sponsor',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/business-sponsor.svg',
      completed: false,
    },
    {
      label: 'Budget details',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/budget-details.svg',
      completed: false,
    },
    {
      label: 'Stakeholders',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/stakeholders.svg',
      completed: false,
    },
    {
      label: 'Out of scope',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/scope.svg',
      completed: false,
    },
    {
      label: 'Business case impacts',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/business-case-impact.svg',
      completed: false,
    },
    {
      label: 'Portfolio alignment',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/portfolio-alignment.svg',
      completed: false,
    },
    {
      label: 'IT sponsor',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/it-sponsor.svg',
      completed: false,
    },
    {
      label: 'Additional attachments',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/additional-attachments.svg',
      completed: false,
    },
    {
      label: 'Additional comments',
      value: '',
      valid: false,
      editing: false,
      image: 'assets/images/additional-comments.svg',
      completed: false,
    },
  ],
  First_Time_User: {
    welcomeMess: 'Hi! 👋 Good morning John Doe!',
    filled: 'See what needs to be filled?',
    INTRO_MESSAGES: [
      '👋 Hi, I’m ADA (AI Digital Assistant)!',
      '💡 I help shape and refine your Business Idea.',
      '⚡ Based on your input, I generate key details instantly.',
      '🎯 My goal? Clear, structured content to set you up for success!',
      '🚀 Let’s bring your idea to life!',
    ],
    createNew: 'Create new business idea',
  },
  User_Request: {
    title: 'My requests',
    noRequest: 'You have no request created',
    TABLE_HEADERS: [
      'Request number',
      'Idea title',
      'Submitted date',
      'Last updated',
      'Total no questions completed',
      'Comments',
      'Status',
    ],
    createNew: 'Create new business idea',
  },
  User_Request_Details: {
    summary: 'Summary',
    idea: 'Your idea',
    wish: 'If you wish to',
    changes: 'make any changes',
    updated: ', you can still update the information through',
    ada: 'ADA conversations',
    team: '. The team will always consider the latest details provided.',
    canvas: 'Business Idea Canvas',
    review: 'Pending review',
    reviewText: 'Your idea is pending view with SPPM team 07 Jan 2025',
    feedback: 'Feedback',
    feedbackText:
      "If it's not accepted, you might get feedback to revise the idea",
    accepted: 'Accepted',
    acceptedText: "If your idea is reviewed, it'll get accepted directly",
    request: 'Request number',
    status: 'Status',
    date: 'Submitted date',
    last: 'Last updated',
    completedQuestions: 'Total no questions completed',
    comments: 'Comments',
  },
};
